--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TheClimbing/RPGLike
build-by-default: true
branches:
- master
projects:
  RPGLike:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
...
